<?php

/**
 * Theme hook
 */
function lista_post_theme($existing, $type, $theme, $path) {
     
    return array(
        'lista_post' => array(
                                'variables' => array(
                                    'titulo' => 'Título por defecto',
                                    'posts'   => NULL
                                    ),
                                'template' => 'lista_post'
        )
    );
}


